# Resultats statistiques

In [1]:
import numpy as np
from Graphe_OO.Graph import Graph
from Graphe_OO.Algorithmes_Approches import AlgoMatrice
from Graphe_OO.Heuristique_BAB_OO import *
import pandas as pd
import seaborn as sns

In [2]:
from Graphe_Adjacence.Graph2 import Graph_A
from Graphe_Adjacence.Algorithmes_Approches2 import AlgoAdjacence
from Graphe_Adjacence.Heuristique_BAB import *

In [3]:
file = r"test2.txt"

## Lecture graph

### Matrice

In [4]:

G_Matrice = Graph(0, 0, file=file)

print(G_Matrice.etiquettes)
print(G_Matrice.adjacence)
print(G_Matrice.arretes)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 1. 0.]]
[('1', '2'), ('1', '6'), ('1', '8'), ('2', '3'), ('2', '8'), ('4', '5'), ('4', '6'), ('4', '9'), ('6', '7'), ('6', '8'), ('6', '9'), ('8', '9')]


### Adjacence

In [5]:

G_Adjacent = Graph_A(0,0, file=file)

print(G_Adjacent.n)
print(G_Adjacent.m)
print(G_Adjacent.adjacence_list)
print(G_Adjacent.arretes)

10
12
{'0': [], '1': ['2', '6', '8'], '2': ['1', '3', '8'], '3': ['2'], '4': ['5', '6', '9'], '5': ['4'], '6': ['1', '4', '7', '8', '9'], '7': ['6'], '8': ['1', '2', '6', '9'], '9': ['4', '6', '8']}
[('1', '2'), ('1', '6'), ('1', '8'), ('2', '3'), ('2', '8'), ('4', '5'), ('4', '6'), ('4', '9'), ('6', '7'), ('6', '8'), ('6', '9'), ('8', '9')]


## Algo Glouton

### Matrice

In [6]:
print(AlgoMatrice.algo_glouton(G_Matrice))

['6', '2', '4', '8']


### Adjacence

In [7]:
print(AlgoAdjacence.algo_glouton(G_Adjacent))

['6', '2', '4', '8']


## Algo Couplage

### Matrice

In [8]:
print(AlgoMatrice.algo_couplage(G_Matrice))

['1', '2', '4', '5', '6', '7', '8', '9']


### Adjacence

In [9]:
print(AlgoAdjacence.algo_couplage(G_Adjacent))

['1', '2', '4', '5', '6', '7', '8', '9']


## Algo Branchement

### Matrice

#### Recursive

In [10]:
print(AlgoMatrice.branchement(G_Matrice))

['2', '6', '8', '4']


#### Pile

In [11]:
print(parcours_profondeur_NB_lite_OO(G_Matrice))

['2', '6', '8', '4']


### Adjacence

In [12]:
print(parcours_profondeur_NB_lite(G_Adjacent))

['2', '6', '8', '4']


## Algo Branchement Borné

### Matrice

In [13]:
print(parcours_profondeur_lite_OO(G_Matrice))

['2', '6', '8', '4']


### Adjacence

In [14]:
print(parcours_profondeur_lite(G_Adjacent))

['2', '6', '8', '4']


In [15]:
print(parcours_profondeur_lite_glouton(G_Adjacent))

['6', '2', '4', '8']


## Algo Branchement Borné Amélioré

### Matrice

In [16]:
print(parcours_profondeur_lite_ameliore_1_OO(G_Matrice))


['2', '6', '8', '4']


In [17]:
print(parcours_profondeur_lite_ameliore_2(G_Adjacent))

['1', '4', '6', '2', '8']


### Adjacence

In [18]:
print(parcours_profondeur_lite_ameliore_1(G_Adjacent))

['2', '6', '8', '4']


In [19]:
print(parcours_profondeur_lite_ameliore_2(G_Adjacent))

['1', '4', '6', '2', '8']
